version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=$burkay.sevilmis@gmail.com --password=$1dc1130a-d453-46e7-9c9f-017e423713af registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$movie-brk/web
         docker push registry.heroku.com/$movie-brk/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $movie-brk